colorScheme = "avocado"
enableSearch = true
enableCodeCopy = true

homepage.layout = "profile"
homepage.showRecent = true

[article]
  showDate = true
  showDateUpdated = true
  showEdit = true
  editURL = "https://github.com/saburto/saburto.github.io/edit/main/content/"
  showBreadcrumbs  = false
  showTableOfContents = true
  showTaxonomies = true

[list]
  showTableOfContents = false
  showSummary = true
  showTaxonomies = true