baseURL = "https://www.saburto.com/"

defaultContentLanguage = "en"
title = "Seba's blog"
enableGitInfo = true
enableRobotsTXT = true

theme = "hugo-book"

staticDir = ["static"]

[markup]
  [markup.highlight]
    noclasses = false

[markup.goldmark.renderer]
  unsafe = true

[languages]
  [languages.en]
    title = "Seba's blog"
    languageCode = "en"
    languageName = "English"
    staticDir = ["static"]
    weight = 1
    [[languages.en.menu.before]]
      identifier = "posts"
      pageRef = "/posts/"
      weight = 2
  [languages.es]
    title = "El blog del Seba"
    languageCode = "es"
    languageName = "Español"
    staticDir = ["static"]
    weight = 2

    [languages.es.params.home.profile]
      enable = true
      title = "Blog de Sebastian Aburto"
      subtitle = "Posts sobre programación y desarrollo de software en general."
      social = true
      disclaimer = "El contenido en este sitio es mío y no necesariamente representa la posición, estratégica u opinión de mi actual empleador"
      gravatarEmail = "seba.aburto@gmail.com"
      typeit = true
    [[languages.es.menu.before]]
      identifier = "posts"
      pageRef = "/posts/"
      weight = 2

[params]
  BookTheme = 'auto'
  BookToc = true
  BookSection = '/categories'
  BookEditPath = 'edit/main'
  BookCommitPath = 'commit'
  BookRepo = 'https://github.com/saburto/saburto.github.io'
  BookDateFormat = 'Jan 2, 2006'

  about = "Sebastian Aburto's blog"
  description = "Content about programming and software development in general"
  version = "0.2.X"
  gitRepo = "https://github.com/saburto/saburto.github.io"
  dateFormat = "2006-01-02"

[params.home.profile]
  enable = true
  title = "Sebastian Aburto's blog"
  subtitle = "Content about programming and software development in general"
  disclaimer = "The posts on this site are my own and don’t necessarily represent my current employer positions, strategies, or opinions."
  gravatarEmail = "seba.aburto@gmail.com"

[params.social]
  GitHub = "saburto"
  Linkedin = "saburto"

[params.search]
  enable = true
  type = "lunr"
  contentLength = 4000
  placeholder = ""
  maxResultLength = 10
  snippetLength = 30
  highlightTag = "em"
  absoluteURL = false

[params.list]
    paginate = 10
    dateFormat = "02 Jan"

[params.page]
    linkToMarkdown = true

[params.page.code]
    copy = true
    maxShownLines = 10000


[params.page.share]
  enable = true
  Twitter = true
  Linkedin = true
  HackerNews = true
  Reddit = true


[author]
  name = "Sebastian Aburto"

[params.footer]
  enable = true
  custom = ''
  since = 2021

[params.section]
  paginate = 10
  dateFormat = "January 2006"
  rss = 10

# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
