name: Test deployment

on:
  pull_request:
    branches: [main]

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install, build, and upload Astro assets
        uses: withastro/action@v3
